### PR TITLE
Add Unity 6.5 compatibility for GetEntityId

### LINKED ISSUE #45: Unity 6.5 compatibility: Object.GetInstanceID() causes compilation errors
## Summary

UnityScreenNavigator does not compile on Unity 6.5 because it uses `Object.GetInstanceID()`.

`GetInstanceID()` was marked as obsolete in Unity 6.4 and causes compilation errors in Unity 6.5.

## Environment

- Unity 6.3: Works
- Unity 6.4: Works (obsolete warning)
- Unity 6.5: Compilation error

## Cause

The following classes use `Object.GetInstanceID()` as the key for instance caches:

- `PageContainer`
- `ModalContainer`
- `SheetContainer`

In Unity 6.5, `GetInstanceID()` should be replaced with `GetEntityId()`, and the dictionary key type should be changed from `int` to `EntityId`.

## Additional information

I have already verified this change in my fork, and UnityScreenNavigator compiles and works correctly on Unity 6.5 after updating these classes.

A pull request with this fix will follow shortly.

### PR DESCRIPTION
**Pull request by mingos**
Fixes #45

## Summary

This PR adds compatibility with Unity 6.5 by replacing `GetInstanceID()` with `GetEntityId()` where required.

To preserve compatibility with earlier Unity versions, conditional compilation is used:

- Unity 6.5 or newer: `GetEntityId()` / `EntityId`
- Unity 6.3 and 6.4: `GetInstanceID()` / `int`

## Changes

Updated the following classes:

- `PageContainer`
- `ModalContainer`
- `SheetContainer`

## Tested

- Unity 6.5: Compiles successfully
- Unity 6.4: Existing implementation is preserved through conditional compilation

### CODE REVIEW

**Comment by Haruma-K** [comment]
Sorry it took me a while to get to this — I’ve merged the PR now. Thanks so much!
